site_name: LanceDB Docs
site_url: https://lancedb.github.io/lancedb/
repo_url: https://github.com/lancedb/lancedb
edit_uri: https://github.com/lancedb/lancedb/tree/main/docs/src
repo_name: lancedb/lancedb
docs_dir: src

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - toc.follow
    - toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [../python]
        selection:
          docstring_style: numpy
        rendering:
          heading_level: 4
          show_source: true
          show_symbol_type_in_heading: true
          show_signature_annotations: true
          show_root_heading: true
          members_order: source
        import:
          # for cross references
          - https://arrow.apache.org/docs/objects.inv
          - https://pandas.pydata.org/docs/objects.inv
- mkdocs-jupyter

markdown_extensions:
- admonition
- footnotes
- pymdownx.superfences
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- md_in_html

nav:
- Home:
  - 🏢 Home: index.md
  - 💡 Basics: basic.md
  - 📚 Guides:
    - Create Ingest Update Delete: guides/tables.md
    - Vector Search: search.md
    - SQL filters: sql.md
    - Indexing: ann_indexes.md
    - Versioning & Reproducibility: notebooks/reproducibility.ipynb
  - 🧬 Embeddings:
    - embeddings/index.md
    - Ingest Embedding Functions: embeddings/embedding_functions.md
    - Available Functions: embeddings/default_embedding_functions.md
    - Create Custom Embedding Functions: embeddings/api.md
    - Example - Multi-lingual semantic search: notebooks/multi_lingual_example.ipynb
    - Example - MultiModal CLIP Embeddings: notebooks/DisappearingEmbeddingFunction.ipynb
  - 🔍 Python full-text search: fts.md
  - 🔌 Integrations:
    - integrations/index.md
    - Pandas and PyArrow: python/arrow.md
    - DuckDB: python/duckdb.md
    - LangChain 🔗: https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/lancedb.html
    - LangChain JS/TS 🔗: https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/lancedb
    - LlamaIndex 🦙: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/LanceDBIndexDemo.html
    - Pydantic: python/pydantic.md
    - Voxel51: integrations/voxel51.md
    - PromptTools: integrations/prompttools.md
  - 🐍 Python examples:
    - examples/index.md
    - YouTube Transcript Search: notebooks/youtube_transcript_search.ipynb
    - Documentation QA Bot using LangChain: notebooks/code_qa_bot.ipynb
    - Multimodal search using CLIP: notebooks/multimodal_search.ipynb
    - Example - Calculate CLIP Embeddings with Roboflow Inference: examples/image_embeddings_roboflow.md
    - Serverless QA Bot with S3 and Lambda: examples/serverless_lancedb_with_s3_and_lambda.md
    - Serverless QA Bot with Modal: examples/serverless_qa_bot_with_modal_and_langchain.md
  - 🌐 Javascript examples:
    - Examples: examples/index_js.md
    - Serverless Website Chatbot: examples/serverless_website_chatbot.md
    - YouTube Transcript Search: examples/youtube_transcript_bot_with_nodejs.md
    - TransformersJS Embedding Search: examples/transformerjs_embedding_search_nodejs.md
  - ⚙️ CLI & Config: cli_config.md

- Basics: basic.md
- Guides:
  - Create Ingest Update Delete: guides/tables.md
  - Vector Search: search.md
  - SQL filters: sql.md
  - Indexing: ann_indexes.md
  - Versioning & Reproducibility: notebooks/reproducibility.ipynb
- Embeddings:
  - embeddings/index.md
  - Ingest Embedding Functions: embeddings/embedding_functions.md
  - Available Functions: embeddings/default_embedding_functions.md
  - Create Custom Embedding Functions: embeddings/api.md
  - Example - Multi-lingual semantic search: notebooks/multi_lingual_example.ipynb
  - Example - MultiModal CLIP Embeddings: notebooks/DisappearingEmbeddingFunction.ipynb
- Python full-text search: fts.md
- Integrations:
  - integrations/index.md
  - Pandas and PyArrow: python/arrow.md
  - DuckDB: python/duckdb.md
  - LangChain 🦜️🔗: https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/lancedb.html
  - LangChain JS/TS 🦜️🔗: https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/lancedb
  - LlamaIndex 🦙: https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/LanceDBIndexDemo.html
  - Pydantic: python/pydantic.md
  - Voxel51: integrations/voxel51.md
  - PromptTools: integrations/prompttools.md
- Python examples:
  - examples/index.md
  - YouTube Transcript Search: notebooks/youtube_transcript_search.ipynb
  - Documentation QA Bot using LangChain: notebooks/code_qa_bot.ipynb
  - Multimodal search using CLIP: notebooks/multimodal_search.ipynb
  - Serverless QA Bot with S3 and Lambda: examples/serverless_lancedb_with_s3_and_lambda.md
  - Serverless QA Bot with Modal: examples/serverless_qa_bot_with_modal_and_langchain.md
- Javascript examples:
  - examples/index_js.md
  - YouTube Transcript Search: examples/youtube_transcript_bot_with_nodejs.md
  - Serverless Chatbot from any website: examples/serverless_website_chatbot.md
  - TransformersJS Embedding Search: examples/transformerjs_embedding_search_nodejs.md
- API references:
  - OSS Python API: python/python.md
  - SaaS Python API: python/saas-python.md
  - Javascript API: javascript/modules.md
- LanceDB Cloud↗: https://noteforms.com/forms/lancedb-mailing-list-cloud-kty1o5?notionforms=1&utm_source=notionforms

extra_css:
  - styles/global.css

extra:
  analytics:
    provider: google
    property: G-B7NFM40W74
